import 'package:flutter/material.dart';
import 'package:supabase_project/CommonWidgets/static_page_shared_widgets.dart';
import 'package:supabase_project/ConstantTexts/Theme.dart';
import 'package:supabase_project/ConstantTexts/final_texts.dart';
import '../../CommonWidgets/bottom-navigation-bar.dart';
import '../../CommonWidgets/appbar-widget.dart';

class RenewableEnergy extends StatefulWidget {
  const RenewableEnergy({super.key, required int selectedIndex});

  @override
  _RenewableEnergyState createState() => _RenewableEnergyState();
}

class _RenewableEnergyState extends State<RenewableEnergy> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.getAppTheme(),
      home: Scaffold(
        appBar: customAppBar1(
          title: 'Renewable Energy',
          onBackPressed: () {
            Navigator.pop(context);
          },
        ),

        // bottomNavigationBar: customBottomNavigationBar(onTap: (int) {}),
        body: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              firstParagraph(context, renewableEnergyP1),
              firstParagraph(context, renewableEnergyP2),
              bigImageContainer(context, 'assets/image0.png'),
              header(context, 'Types of Renewable Energy'),
              bottomDescription(
                context,
                'Solar Energy',
                'Harnessed from the sun using solar panels.',
                'Used for electricity, heating, and even transportation.',
                'assets/energy1.png',
                true,
              ),
              bottomDescription(
                context,
                'WIND ENERGY',
                'Generated by wind turbines converting wind power into electricity.',
                'Ideal for areas with strong, consistent winds.',
                'assets/energy1.png',
                false,
              ),
              bottomDescription(
                context,
                'HYDROPOWER',
                'Produced by the movement of water in rivers and dams.',
                'A reliable source of large-scale electricity generation.',
                'assets/energy1.png',
                true,
              ),
              bottomDescription(
                context,
                'GEOTHERMAL ENERGY',
                'Sourced from the heat within the Earth.',
                'Used for electricity and direct heating applications.',
                'assets/energy1.png',
                false,
              ),
              bottomDescription(
                context,
                'BIOMASS ENERGY',
                'Derived from organic materials like plant and animal waste.',
                'Can be converted into biofuels for transportation and power generation.',
                'assets/energy1.png',
                true,
              ),
              header(context, 'Benefits of Renewable Energy'),
              benefits(
                context,
                '1. Cost Savings. Lower energy bills due to reduced energy consumption.',
                '2. Environmental Impact. Decreases greenhouse gas emissions and pollution.',
                '3. Increased Comfort. Better insulation and efficient systems enhance living conditions.',
                '4. Enhanced Energy Security. Reduces dependence on imported energy.',
              ),
              header(context, 'How can you contribute?'),
              benefits(
                context,
                'Upgrade your Appliances. Choose energy-efficient models when replacing old appliances.',
                'Conduct Energy Audits. Regularly check your home for energy efficiency improvements.',
                'Support Green Initiatives. Advocate for and participate in local energy-saving programs',
                '',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
